### ISSUE TITLE
Dist Folder neccessary?

### ISSUE THREAD

**Issue by flwall** [MrTob/ToDo-WebApp#1]
Why is it neccessary to include Sass compile output (css) in this repository and commit it.
Can't you have an automated compile of the sass files for the GitHub pages site?

**Comment by MrTob** [comment]
As a rule of thumb, you can say that only the source files are pushed into the repo.
However, this requires me to use something like a continuous integration pipeline that compiles the assets on deployment.
For the size of the project, I think it's a bit overkill to use a continuous integration, so it' s easier to push the ".sass" and ".css" files
